# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherAlarm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'AlamofireImage', '~> 3.2'
    pod 'AlamofireObjectMapper', '~> 4.1'
    pod 'ObjectMapper', '~> 2.2'
    pod 'Firebase'
    pod 'FirebaseAuth'
    pod 'FirebaseDatabase'
    pod 'GoogleSignIn'
    pod 'Firebase/Database'
  # Pods for WeatherAlarm

  target 'WeatherAlarmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherAlarmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
